name: Publish to Packagist

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist
        
      - name: Verify package
        run: composer validate
        
      - name: Notify Packagist
        run: |
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"repository":{"url":"https://packagist.org/packages/laravel-theme-detector"}}' \
          "https://packagist.org/api/update-package?username=TU_USUARIO&apiToken=TU_TOKEN"
          